version: '2'

services:

  # Build the container using the app Dockerfile
  app:
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    
    volumes:
      - ./app/app:/usr/src/app/app
    ports:
      - "3000:3000"
    links:
      - mongo
  
  # Build the container using the nginx Dockerfile
  nginx:
    build:
      context: ./nginx
      args: 
        config: default.conf
    ports:
      - "80:80"
    links: 
      - app
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --bind_ip 0.0.0.0 -v