version: '2'

services:

  # Build the container using the app Dockerfile
  app:
    build:
      context: ./app
      dockerfile: Dockerfile-prod
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    links:
      - mongo
  
  # Build the container using the nginx Dockerfile
  nginx:
    image: garethf89/portfolio_nginx
    build:
      context: ./
      args: 
        config: /prod.conf
    ports:
      - "80:80"
      - “443:443”
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    links: 
      - app
      - mongo

  certbot:
    image: certbot/certbot\
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --bind_ip 0.0.0.0 -v